# Generated by Django 6.0.6 on 2026-06-27 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectDebitMandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomba_mandate_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_debit_mandates', to='groups.groupmembership')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('payment_method', models.CharField(choices=[('va_transfer', 'Bank Transfer to VA'), ('direct_debit', 'Direct Debit'), ('save_ahead', 'Save-Ahead Wallet')], default='va_transfer', max_length=14)),
                ('nomba_transaction_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('nomba_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='groups.groupcycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='groups.groupmembership')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('cycle', 'member')},
            },
        ),
    ]
